### ISSUE TITLE
Failed to install script

### ISSUE THREAD

**Issue by MammadTavakoli** [atom-ide-community/atom-script#1020]
when I try yo install it, it make this error :

> Failed to install script because Git was not found.
> 
> The script package has module dependencies that cannot be installed without Git.
> 
> You need to install Git and add it to your path environment variable in order to install this package.
> 
> You can install Git by downloading, installing, and launching GitHub for Windows: https://windows.github.com
> 
> Run apm -v after installing Git to see what version has been detected.

**Comment by Akumetsu-Dev** [comment]
First download and install https://windows.github.com

after follow this steps

1- C:\Users\<NameofUser>\AppData\Local\GitHub\PortableGit_<Serial>, in this folder you will find a batch named post-install you have to install it with admin permission.

2- Add to the environment variable the next path:
- C:\Users\<NameofUser>\AppData\Local\GitHub\PortableGit_PortableGit_<Serial>\usr\bin
- C:\Users\<NameofUser>\AppData\Local\GitHub\PortableGit_PortableGit_<Serial>\etc\ssh
- C:\Users\<NameofUser>\AppData\Local\GitHub\PortableGit_PortableGit_<Serial>\cmd
                    *GitHub didnt do this after the instalation, you have to do it manual.
![image](https://cloud.githubusercontent.com/assets/7697566/17557424/248b2978-5ee5-11e6-8e68-36bea6692561.png)

3- In the C:\Users\<NameofUser>\AppData\Local\GitHub\PortableGit_PortableGit_<Serial>\cmd, you will find 2 *.cmd files: "start-ssh-agent" and "start-ssh-pageant" run in with admin permission.
![image](https://cloud.githubusercontent.com/assets/7697566/17557449/3e3469ac-5ee5-11e6-94a6-2054c0fd363a.png)

4- Reboot windows and try install script.
