### ISSUE TITLE
Installing “script@3.8.3” failed

### ISSUE THREAD

**Issue by atkmojo** [atom-ide-community/atom-script#1031]
npm ERR! git clone --template=/home/atik/.atom/.apm/_git-remotes/_templates --mirror git://github.com/monsterkodi/node-simple-plist.git /home/atik/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541: Cloning into bare repository '/home/atik/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! git clone --template=/home/atik/.atom/.apm/_git-remotes/_templates --mirror git://github.com/monsterkodi/node-simple-plist.git /home/atik/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541: fatal: unable to connect to github.com:
npm ERR! git clone --template=/home/atik/.atom/.apm/_git-remotes/_templates --mirror git://github.com/monsterkodi/node-simple-plist.git /home/atik/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541: github.com[0: 192.30.253.112]: errno=Connection refused
npm ERR! Linux 4.6.4-201.fc23.x86_64
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/atik/.atom/.apm/.apmrc" "--userconfig" "/home/atik/.atom/.apmrc" "install" "/tmp/d-11675-4222-4tb3kc/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository '/home/atik/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.112]: errno=Connection refused
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11675-4222-poeaj7/npm-debug.log

**Comment by Akumetsu-Dev** [comment]
Hello, i found the solution, firt GitHub windows Client not installed completely, what i mean the next step below, the installation process had to do it automatic, but did not.

1- C:\Users\<NameofUser>\AppData\Local\GitHub\PortableGit_<Serial>, in this folder you will find a batch named post-install you have to install it with admin permission.

2- Add to the environment variable the next path:
- C:\Users\<NameofUser>\AppData\Local\GitHub\PortableGit_PortableGit_<Serial>\usr\bin
- C:\Users\<NameofUser>\AppData\Local\GitHub\PortableGit_PortableGit_<Serial>\etc\ssh
- C:\Users\<NameofUser>\AppData\Local\GitHub\PortableGit_PortableGit_<Serial>\cmd
                    *GitHub didnt do this after the instalation, you have to do it manual.
![image](https://cloud.githubusercontent.com/assets/7697566/17557424/248b2978-5ee5-11e6-8e68-36bea6692561.png)

3- In the C:\Users\<NameofUser>\AppData\Local\GitHub\PortableGit_PortableGit_<Serial>\cmd, you will find 2 *.cmd files: "start-ssh-agent" and "start-ssh-pageant" run in with admin permission.
![image](https://cloud.githubusercontent.com/assets/7697566/17557449/3e3469ac-5ee5-11e6-94a6-2054c0fd363a.png)

4- Reboot windows and try install script.
