### ISSUE TITLE
Add support for fsharp

### ISSUE THREAD

**Issue by gutoboranga** [atom-ide-community/atom-script#1034]
It says that supports F#, but shows me "Command not configured for fsharp!" every time I try to run a .fs script.

**Comment by nixel2007** [comment]
Looks like you use different f# package. This package looks to "F#" syntax, and your package provides "fsharp"

**Comment by Elinvention** [comment]
@nixel2007 which fsharp package? I installed ionide-installer.

**Comment by nixel2007** [comment]
@Elinvention this one, i suppose https://atom.io/packages/language-fsharp

**Comment by nixel2007** [comment]
we can add another f# entry with 'fsharp' scope, if `ionide` provides better syntax or more usefull things to coding proccess in f#.
