### ISSUE TITLE
Installing "script@8.2.3" failed.

### ISSUE THREAD

**Issue by StupendousMe** [atom-ide-community/atom-script#1043]
npm WARN addRemoteGit git://github.com/monsterkodi/node-simple-plist.git resetting remote /Users/marcelgrant/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541 because of error: Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm ERR! git clone --template=/Users/marcelgrant/.atom/.apm/_git-remotes/_templates --mirror git://github.com/monsterkodi/node-simple-plist.git /Users/marcelgrant/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541: Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm ERR! Darwin 15.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/marcelgrant/.atom/.apm/.apmrc" "--userconfig" "/Users/marcelgrant/.atom/.apmrc" "install" "/private/var/folders/6_/vm4mvdqn2z92nz3ktj167qmh0000gn/T/d-116713-5099-c0cdnr/package.tgz" "--target=0.37.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 69

npm ERR! Command failed: 
npm ERR! 
npm ERR! Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/6_/vm4mvdqn2z92nz3ktj167qmh0000gn/T/apm-install-dir-116713-5099-1sbzc9h/npm-debug.log

What do I do? Any other way to run scripts?

**Comment by Akumetsu-Dev** [comment]
https://github.com/rgbkrk/atom-script/issues/1039 --> try this.
