### ISSUE TITLE
Add support for R (https://www.r-project.org/)

### ISSUE THREAD

**Issue by sumanstats** [atom-ide-community/atom-script#1351]
Hi there, 

I was surprised to see no support for R (https://www.r-project.org/ ) in atom from script !! Could you please consider adding support for R. Its rapidly growing language among data scientists and programmers alike. It will surely help R community. 

Regards,

**Comment by bodak** [comment]
Atom-script already has R support through rscript execution 👍

Check if you have language-r [https://atom.io/packages/language-r](url) package installed.
