### ISSUE TITLE
Add support for Python Console

### ISSUE THREAD

**Issue by Carnimal** [atom-ide-community/atom-script#1374]
I downloaded python and started using atom as my text editor, started with some light coding to get used to the program, but it shows that 'python' is not recognized as an internal or external command,
operable program or batch file. pls help and thank you.

**Comment by danPadric** [comment]
Hi. 

It is not the fault of this add-on or that of the Atom IDE. 

I also had this problem on my Windows system - I will assume you have Windows too. Quickest way is to uninstall your Python and then re-install it. There is an option you missed. Ensure then that Python is "rooted" in the proper way.

Test your installation. Run the command prompt (WIN+R; type: CMD) for Windows. Type "Python" and hit return. Python should start-up in prompt mode. Enter "exit()" to exit Python's prompt mode and then "exit" to exit Windows' prompt.

I suggest you get going with IDLE (standard installed with Python) at first. Learn a little about Python first before attempting Atom with it. There are a few not so nicely documented things you should know of the add-ons for Atom before using it makes sense.

Regards.

**Comment by danPadric** [comment]
To Admin: This topic can be closed as it is not a problem for you to attend to.
