### ISSUE TITLE
Add support for Python

### ISSUE THREAD

**Issue by adeyemosot** [atom-ide-community/atom-script#1594]
I could not run Python scripts on ATOM. I have been using applications including Notepad++ and Jupyter Notebook and my scripts have been running fine. I decided to move to Atom now and has been facing environmental challenges. There is no issue with my python installation and the script package in ATOM has been edited to allow for python 3 as below:

#exports.Python =
Python:
  'Selection Based':
    command: 'python3'
    args: (context) -> ['-u', '-c', context.getCode()]

  'File Based':
    command: 'python3'
    args: (context) -> ['-u', context.filepath]

exports.MagicPython = exports.Python

exports.Sage =
  'Selection Based':
    command: 'sage'
    args: (context) -> ['-c', context.getCode()]

  'File Based':
    command: 'sage'
    args: (context) -> [context.filepath]

The error I am getting when I try to run the simplest script is:
" Command not configured for Python!

Add an issue on GitHub or send your own Pull Request.

^C"

Kindly assist me to resolve the issue ASAP

**Comment by JBallin** [comment]
If you type `which python3` in Terminal, what do you get? If you don't get anything you likely haven't installed it. If you have a mac you can use homebrew: `brew install python`.
