### ISSUE TITLE
Add support for C  ++

### ISSUE THREAD

**Issue by ericcleee** [atom-ide-community/atom-script#1692]
i tried writing and running a c++ code on atom for the first time.
i have download and installed MinGW, my g++ is working fine in my cmd. I have installed gpp-complier on atom. 

when i try and run the code, this error appears in the cmd pop up,

/'C:\Users\ericl\AppData\Local\Temp\hello' is not recognized as an internal or external command,
operable program or batch file.

Press any key to continue . . .

My code:
/
#include <iostream>
using namespace std;

int main()
{
cout << "Hello world";
return 0;
}
/

**Comment by DamnedScholar** [comment]
Is `C:\Users\ericl\AppData\Local\Temp\hello` the name of your code file? If so, you should add the `.cpp` file extension. In either case, you should not store your code files inside `AppData`.
