### ISSUE TITLE
Script package on Atom does not work for javascript

### ISSUE THREAD

**Issue by FelixChen78** [atom-ide-community/atom-script#1831]
I get this when I press cmd I

bash: node: command not found
env: node: No such file or directory
[Finished in 0.02s]

Script package works fine for python so I am wondering if there's a simple fix

**Comment by mativ123** [comment]
me to

**Comment by EbrahimKaram** [comment]
> I get this when I press cmd I
> 
> bash: node: command not found
> env: node: No such file or directory
> [Finished in 0.02s]
> 
> Script package works fine for python so I am wondering if there's a simple fix

The issue according to atoms discussions is that there is a space in the name of the file or path to the file. 

Try running it where in another location with no space
