### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by SpaceLens** [atom-ide-community/atom-script#1997]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 18.04.3
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.25.0

### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At /home/paul/.atom/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189

TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
    at ScriptView.detach (/packages/open-in-browsers/node_modules/jquery/dist/jquery.js:5357:15)
    at ScriptView.removePanel (/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (/packages/script/lib/script.js:161:21)
    at HTMLElement.scriptCloseView (/packages/script/lib/script.js:94:39)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:349123)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/static/<embedded>:11:347598)
    at ScriptView.close (/packages/script/lib/script-view.js:99:19)
    at /packages/open-in-browsers/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLDivElement.dispatch (/packages/open-in-browsers/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/open-in-browsers/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  4x -0:24.8.0 core:save (input.hidden-input)
     -0:22.7.0 core:close (input.hidden-input)
     -0:22 editor:consolidate-selections (input.hidden-input)
     -0:22 core:cancel (input.hidden-input)
     -0:21.4.0 editor:consolidate-selections (input.hidden-input)
     -0:21.4.0 core:cancel (input.hidden-input)
     -0:21.2.0 editor:consolidate-selections (input.hidden-input)
     -0:21.2.0 core:cancel (input.hidden-input)
     -0:21.1.0 editor:consolidate-selections (input.hidden-input)
     -0:21.1.0 core:cancel (input.hidden-input)
     -0:20.9.0 editor:consolidate-selections (input.hidden-input)
     -0:20.9.0 core:cancel (input.hidden-input)
     -0:20.7.0 editor:consolidate-selections (input.hidden-input)
     -0:20.7.0 core:cancel (input.hidden-input)
     -0:14.3.0 core:close (atom-pane.pane.active)
     -0:05.7.0 script:close-view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
emmet 2.4.3 
open-in-browsers 0.0.30 
script 3.25.0 
```

**Comment by vsharm29** [comment]
when ever I try to run my code by pressing keys ctrl + shift + B. The down pane opens up and shows output of the code. When ever I try to close the pane it raises an error. Please look into this issue, it's very irritating.

**Comment by Pixel48** [comment]
Im trying to fix this, but for know fou can use ctrl-shift-f5. And i know, it's not solution

> when ever I try to run my code by pressing keys ctrl + shift + B. The down pane opens up and shows output of the code. When ever I try to close the pane it raises an error. Please look into this issue, it's very irritating.

**Comment by JordanTheDodger** [comment]
I am getting the same error. It was fine until yesterday. I think there is something wrong with the library that deals with MessagePanelView

**Comment by shreyasgaonkar** [comment]
This shows up on other keyboard shortcuts not dealing with the module as well. Not able to close active tabs using ```cmd + w``` is really annoying

**Comment by Talon24** [comment]
When the output window is stuck already, i also get an error thrown when I press ESC

**Comment by VinnieM** [comment]
This same issue is happening in Mac OS as well.
Atom: 1.41.0
OS : Catalina 10.15.1.

**Comment by PractitionerXM** [comment]
The same error occurs when I try to kill this process.
Atom 1.41.0 x64，win10

**Comment by mkrd** [comment]
Same issue here

> This same issue is happening in Mac OS as well.
> Atom: 1.41.0
> OS : Catalina 10.15.1.

**Comment by brooksidestudios** [comment]
+1

**Comment by creativecag** [comment]
+1

**Comment by tswinb** [comment]
Same issue here. Windows 10, Atom 1.41.0 x64

**Comment by AStartledRaccoon** [comment]
Same issue, also occurs when I press ESC. Ubuntu 18.04, Atom 1.40.0

**Comment by fdq09eca** [comment]
same with @AStartledRaccoon

**Comment by medardm** [comment]
Still no solution to this issue? :(

**Comment by medardm** [comment]
Here's a temporary solution. Modify line 89 in 
.atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js to 
`MessagePanelView.prototype.remove = function (index) {
  this.messages.splice(-index, 1);
  this.body.children()[index].remove();
};`
to
`MessagePanelView.prototype.remove = function (index) {
  $('.native-key-bindings.script-view').remove();
};`

**Comment by AStartledRaccoon** [comment]
@medardm 's solution worked for me!

**Comment by medardm** [comment]
@AStartledRaccoon I'm glad it worked. :)

**Comment by raffaeleGrandi** [comment]
It works also for me thanks

**Comment by Brolly0204** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.25.0


### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At /Users/jasonli/.atom/packages/script/node_modules/atom-message-panel/lib/MessagePanelView.js:188

**Comment by Sirfanas** [comment]
Thank's @medardm for the fix !
Maybe you could made a pull request to include it ?

**Comment by medardm** [comment]
I will when I find a long term solution. Because the solution I introduced was an adjustment with one of the dependencies, not with the actual package.

**Comment by kimathie** [comment]
When I press escape and or try to close the output panel I get this error.

**Comment by CharaDraemurr** [comment]
@medardm Could you tell us which dependecy you used? So we can use your fix. Thanks!

**Comment by VinnieM** [comment]
@medardm Thanks for the fix!!!

**Comment by kimathie** [comment]
@medardm thanks I hadn't seen that solution. It works

**Comment by m0rtye** [comment]
same issue here, please fix it!
Windows 10 | Atom 1.41.0 x64

**Comment by medardm** [comment]
I didn't change any of the dependencies, just modified a line of code on one of the dependencies of this package, but this is not a long term solution.
> Here's a temporary solution. Modify function in line 187 under
> .atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js
> from
> 
> ```
> MessagePanelView.prototype.remove = function (index) {
>   this.messages.splice(-index, 1);
>   this.body.children()[index].remove();
> };
> ```
> 
> to:
> 
> ```
> MessagePanelView.prototype.remove = function (index) {
>   $('.native-key-bindings.script-view').remove();
> };
> ```

**Comment by Fellox** [comment]
Just downloaded this package and found this bug, please fix it!

**Comment by medardm** [comment]
@Fellox . There's already a PR to fix this issue (#2004). You can review it on your side. I already checked it and it works

**Comment by DeathGOD7** [comment]
> Here's a temporary solution. Modify function in line 187 under
> .atom\packages\script\node_modules\atom-message-panel\lib\MessagePanelView.js
> from
> 
> ```
> MessagePanelView.prototype.remove = function (index) {
>   this.messages.splice(-index, 1);
>   this.body.children()[index].remove();
> };
> ```
> 
> to:
> 
> ```
> MessagePanelView.prototype.remove = function (index) {
>   $('.native-key-bindings.script-view').remove();
> };
> ```

That is the solution for now. Thanks for it. :)

**Comment by hex0x42424242** [comment]
nice bro, works for me.
Thanks!

**Comment by jakelevifulfil** [comment]
This hasn't worked for me :( 

Also, editing the files seems to have no effect, even if I intentionally add syntax errors or just comment out the code. I'm looking in `<Username>\.atom\packages\script\node_modules\atom-message-panel\lib`.

**Comment by creativecag** [comment]
> This hasn't worked for me :(
> 
> Also, editing the files seems to have no effect, even if I intentionally add syntax errors or just comment out the code. I'm looking in `<Username>\.atom\packages\script\node_modules\atom-message-panel\lib`.

I had a similar problem. Gave up on it for now.

**Comment by junepark6** [comment]
I also still have this issue. Panel could be removed after modifying the source as you suggested, but it was only working one time. I mean, if I removed the panel before and run again the script, then I cannot remove the panel.

**Comment by wesgt** [comment]
@junepark6  I had a similar problem.

**Comment by creativecag** [comment]
@wesgt That appears to have worked for me as well. Thanks!

**Comment by jakelevifulfil** [comment]
It fixed itself for me... Didn't make any changes, but all's good now! :)

**Comment by mavericks52** [comment]
@wesgt  I now have a problem after your fix where i cant run the program after i close the script window

**Comment by lazerbolt390** [comment]
@wesgt thanks!
