### ISSUE TITLE
installing script 3.25.0 failed - npm ERR! Maximum call stack size exceeded

### ISSUE THREAD

**Issue by trappitsch** [atom-ide-community/atom-script#2077]
Hi,
Installing atom freshly and trying to install script, installation fails with the output pasted in below. Any ideas? 

Thanks already!

> core-js@2.6.11 postinstall /tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
Aborted
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/script/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/package.json'
npm WARN apm-install-dir-120222-11903-1ldq1ly.q1uo No description
npm WARN apm-install-dir-120222-11903-1ldq1ly.q1uo No repository field.
npm WARN apm-install-dir-120222-11903-1ldq1ly.q1uo No README data
npm WARN apm-install-dir-120222-11903-1ldq1ly.q1uo No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abbrev@1.1.1 (node_modules/script/node_modules/fsevents/node_modules/abbrev):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/abbrev' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.abbrev.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ansi-regex@2.1.1 (node_modules/script/node_modules/fsevents/node_modules/ansi-regex):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/ansi-regex' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.ansi-regex.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: aproba@1.2.0 (node_modules/script/node_modules/fsevents/node_modules/aproba):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/aproba' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.aproba.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: balanced-match@1.0.0 (node_modules/script/node_modules/fsevents/node_modules/balanced-match):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/balanced-match' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.balanced-match.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: chownr@1.1.4 (node_modules/script/node_modules/fsevents/node_modules/chownr):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/chownr' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.chownr.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: code-point-at@1.1.0 (node_modules/script/node_modules/fsevents/node_modules/code-point-at):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/code-point-at' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.code-point-at.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: concat-map@0.0.1 (node_modules/script/node_modules/fsevents/node_modules/concat-map):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/concat-map' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.concat-map.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: console-control-strings@1.1.0 (node_modules/script/node_modules/fsevents/node_modules/console-control-strings):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/console-control-strings' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.console-control-strings.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-util-is@1.0.2 (node_modules/script/node_modules/fsevents/node_modules/core-util-is):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/core-util-is' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.core-util-is.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: deep-extend@0.6.0 (node_modules/script/node_modules/fsevents/node_modules/deep-extend):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/deep-extend' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.deep-extend.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: delegates@1.0.0 (node_modules/script/node_modules/fsevents/node_modules/delegates):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/delegates' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.delegates.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: detect-libc@1.0.3 (node_modules/script/node_modules/fsevents/node_modules/detect-libc):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/detect-libc' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.detect-libc.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs.realpath@1.0.0 (node_modules/script/node_modules/fsevents/node_modules/fs.realpath):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/fs.realpath' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.fs.realpath.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: has-unicode@2.0.1 (node_modules/script/node_modules/fsevents/node_modules/has-unicode):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/has-unicode' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.has-unicode.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: inherits@2.0.4 (node_modules/script/node_modules/fsevents/node_modules/inherits):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/inherits' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.inherits.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ini@1.3.5 (node_modules/script/node_modules/fsevents/node_modules/ini):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/ini' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.ini.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: isarray@1.0.0 (node_modules/script/node_modules/fsevents/node_modules/isarray):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/isarray' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.isarray.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimist@1.2.5 (node_modules/script/node_modules/fsevents/node_modules/minimist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/minimist' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.minimist.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ms@2.1.2 (node_modules/script/node_modules/fsevents/node_modules/ms):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/ms' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.ms.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: npm-normalize-package-bin@1.0.1 (node_modules/script/node_modules/fsevents/node_modules/npm-normalize-package-bin):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/npm-normalize-package-bin' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.npm-normalize-package-bin.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: number-is-nan@1.0.1 (node_modules/script/node_modules/fsevents/node_modules/number-is-nan):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/number-is-nan' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.number-is-nan.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: object-assign@4.1.1 (node_modules/script/node_modules/fsevents/node_modules/object-assign):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/object-assign' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.object-assign.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-homedir@1.0.2 (node_modules/script/node_modules/fsevents/node_modules/os-homedir):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/os-homedir' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.os-homedir.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-tmpdir@1.0.2 (node_modules/script/node_modules/fsevents/node_modules/os-tmpdir):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/os-tmpdir' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.os-tmpdir.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: path-is-absolute@1.0.1 (node_modules/script/node_modules/fsevents/node_modules/path-is-absolute):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/path-is-absolute' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.path-is-absolute.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: process-nextick-args@2.0.1 (node_modules/script/node_modules/fsevents/node_modules/process-nextick-args):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/process-nextick-args' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.process-nextick-args.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safe-buffer@5.1.2 (node_modules/script/node_modules/fsevents/node_modules/safe-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/safe-buffer' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.safe-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safer-buffer@2.1.2 (node_modules/script/node_modules/fsevents/node_modules/safer-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/safer-buffer' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.safer-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sax@1.2.4 (node_modules/script/node_modules/fsevents/node_modules/sax):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/sax' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.sax.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: semver@5.7.1 (node_modules/script/node_modules/fsevents/node_modules/semver):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/semver' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.semver.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: set-blocking@2.0.0 (node_modules/script/node_modules/fsevents/node_modules/set-blocking):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/set-blocking' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.set-blocking.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: signal-exit@3.0.2 (node_modules/script/node_modules/fsevents/node_modules/signal-exit):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/signal-exit' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.signal-exit.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: strip-json-comments@2.0.1 (node_modules/script/node_modules/fsevents/node_modules/strip-json-comments):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/strip-json-comments' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.strip-json-comments.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: util-deprecate@1.0.2 (node_modules/script/node_modules/fsevents/node_modules/util-deprecate):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/util-deprecate' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.util-deprecate.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: wrappy@1.0.2 (node_modules/script/node_modules/fsevents/node_modules/wrappy):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/wrappy' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.wrappy.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: yallist@3.1.1 (node_modules/script/node_modules/fsevents/node_modules/yallist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/yallist' -> '/tmp/apm-install-dir-120222-11903-1ldq1ly.q1uo/node_modules/script/node_modules/fsevents/node_modules/.yallist.DELETE'

npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/reto/.atom/.apm/_logs/2020-03-23T04_46_43_539Z-debug.log

**Comment by spongedoc** [comment]
Same problem here.

**Comment by sebautistam** [comment]
I have the exact same problem; other packages installation are successful. Does anybody have a solution?

**Comment by mcnoat** [comment]
This looks rather similar to my issue

**Comment by saltedcoffeeuwu** [comment]
I'm having the same issue.

**Comment by cdmask** [comment]
Same here..
