### ISSUE TITLE
public class HelloWorld {     public static void main(String []args) {       /* println() function to write Hello, World! */       System.out.println("Hello, World!");         } }

### ISSUE THREAD

**Issue by gcalvin817** [atom-ide-community/atom-script#2287]
##### Platform: `darwin`
---

**Comment by gcalvin817** [comment]
public class HelloWorld { 
   public static void main(String []args) {
      /* println() function to write Hello, World! */
      System.out.println("Hello, World!");     
   }
}

**Comment by AceKiron** [comment]
what's the issue here?
