### ISSUE TITLE
Add Line Number Based support for JavaScript

### ISSUE THREAD

**Issue by lokeshjainRL** [atom-ide-community/atom-script#479]
##### Platform: `darwin`

---

I was trying to  execute this simple JavaSacript logging using script

``` javascript
console.log("Yes Script is amazing");
```

I get the following error.

`Line Number Based runner not available for JavaScript.`

**Comment by julienR2** [comment]
any up or workaround ? I'd be interested too :+1:

**Comment by rgbkrk** [comment]
We need to remove line based (or rename it). It was made for a few specific langs and now has really confusing nomenclature.
