### ISSUE TITLE
Adobe InDesign JSX JavaScript support

### ISSUE THREAD

**Issue by OliverGruenberg** [atom-ide-community/atom-script#627]
Can you please add support for Adobe's ExtendScript Toolkit, which is JavaScript and also has the file suffix .jsx?

What I need is the possibility to add an alternative build system.

Currently my workflow is in Sublime Text 3, like this:
- open the JavaScript file
- hit Cmd-B to run the file with the preselected build system (here Adobe InDesign CC2015)
  --> InDesign runs the script and returns the result

In the sublime package I've seen that sublime handles this by forwarding the active script path as an argument like this:

--usage:
--osascript run.scpt myscript.jsx

on run argv
    set aScriptPath to "#include \"" & item 1 of argv & "\""
    tell application "Adobe InDesign CC 2015"
        do script aScriptPath language javascript
    end tell
end run

**Comment by trych** [comment]
Would also love to see that happen! I'm going to teach a class on ExtendScript this fall and was investigating, if ExtendScript can be executed from it. So there is no way at the moment?

**Comment by nixel2007** [comment]
Does it have a dedicated grammar?

**Comment by trych** [comment]
@aminya Could you give us any hint, why this is closed?
You added the duplicate label, but doing a quick search I cannot find any other issue that either mentions the terms "Extendscript" or "InDesign". Could you refer us to the duplicate in question?

**Comment by aminya** [comment]
@trych Sorry, I ran a bot to remove the duplicate issues. For some reason, it detected this issue as a duplicate.
