### ISSUE TITLE
Add support for KoffeeScript (Meteor)

### ISSUE THREAD

**Issue by abhinav-fourtek** [atom-ide-community/atom-script#709]
My copy of Coffeescript was working perfectly fine in Atom, prior to installing meteorjs but now it gives me the error - "Command not configured for KoffeeScript (Meteor)! ".

Coffeescript is still working fine as far as the terminal repl is concerned but I'd really like to get back on track with the atom+coffeescript+repl combination.

Thanks for helping me out)

**Comment by rgbkrk** [comment]
Interesting, seems like a different language pack is set up for Meteor's CoffeeScript. How do you run `KoffeeScript` at the command line? Same as `coffee`?

**Comment by timkinnane** [comment]
FYI, I was getting this too, but it was due to Atom mis-detecting syntax for the file as KoffeeScript (Meteor). I think that's coming from the [meteor-api](https://atom.io/packages/meteor-api) package. You can just manually set the syntax back to CoffeeScript though and it runs fine.

**Comment by abhi18av** [comment]
Yes, actually I've moved onto SublimeText3 in the meantime.I ts fast and doesn't drain my battery life 

But I certainly like the feedbacks i received in the coding community. Thanks @rgbkrk and @timkinnane
