### ISSUE TITLE
Add support for Tcl

### ISSUE THREAD

**Issue by fiveyears** [atom-ide-community/atom-script#745]
How can I add support for tcl, it would be nice to start my tcl-scripts out of atom!

**Comment by Stormherz** [comment]
@fiveyears you can check `lib/grammars.coffee` for examples of other language support. If running tcl scripts is somewhat simple as `tcl some_tcl_script` - there won't be any problems in adding it. Or you could provide with some tcl documentation of running tcl scripts - I'll check it and let you know about how hard will it be to add support for it

**Comment by fiveyears** [comment]
Thx

**Comment by Francehelder** [comment]
Hello 

I see the file lib/grammars.coffee, but do not know how to add support to tcl.
