### ISSUE TITLE
Duplicate Issues

### ISSUE THREAD

**Issue by EntilZha** [atom-ide-community/atom-script#795]
@rgbkrk was looking through issues out of curiosity and it seems like there are lots of duplicates or extremely similar issues (same title, different platform). Is it fine to close/merge these as duplicates?

**Comment by rgbkrk** [comment]
Totally!

We could also write some code to prevent the semi-automated dupes to occur (the little "we don't support X, please file an issue" dialog)

**Comment by EntilZha** [comment]
Didn't realize that the issues were coming auto generated. Anyway, was looking through issue tracker since might think about writing some CoffeeScript in markdown-preview-plus (not being maintained and want to extend it) or script and noticed the massive number of duplicates.

**Comment by rgbkrk** [comment]
Well done sir!

It's too bad I'm back in Texas now, I was just in Boulder two days ago and could have high fived you.

**Comment by rgbkrk** [comment]
Here's the code that does the issue link creation:

https://github.com/rgbkrk/atom-script/blob/b93b026130f46aa9c625b4a73c7232d6e23222c5/lib/script-view.coffee#L90-L106

**Comment by EntilZha** [comment]
Thats too bad. I am full time in Boulder so let me know if you're in the area again.

**Comment by EntilZha** [comment]
How can you trigger this within atom/script? Would like to see it coming up

**Comment by nixel2007** [comment]
@EntilZha you can try to run C code on win :)

**Comment by rgbkrk** [comment]
Use the run command on a file we don't have support for but for which you have a language pack installed. HTML definitely works.

**Comment by aminya** [comment]
Thanks. I closed most of the duplicate issues using a bot.
