### ISSUE TITLE
Installation error on windows, missing folder from package

### ISSUE THREAD

**Issue by farkass** [atom-ide-community/atom-script#816]
Hi,

I have tried to install your package on a windows machine.
But received an error about missing folder:
npm ERR! enoent ENOENT, open 'C:\Users\farkass\AppData\Local\Temp\1\apm-install-dir-116126-8168-tjmyl7\node_modules\script\node_modules\ansi-to-html\node_modules\karg\Icon
'
Here is the content of node_modules:
02/26/2016  10:32 AM    <DIR>          .
02/26/2016  10:32 AM    <DIR>          ..
02/26/2016  10:32 AM    <DIR>          .bin
02/26/2016  10:32 AM    <DIR>          atom-message-panel
02/26/2016  10:32 AM    <DIR>          atom-space-pen-views
02/26/2016  10:32 AM    <DIR>          node-uuid
02/26/2016  10:32 AM    <DIR>          strip-ansi
02/26/2016  10:32 AM    <DIR>          underscore
               0 File(s)              0 bytes

Folder 'ansi-to-html' is missing completely.

Thanks!

**Comment by viyatgandhi** [comment]
@farkass are you getting same error message as mentioned in issue #815 ? I am also unable to install the script.

**Comment by farkass** [comment]
Checked it, and I think yes, it seems the same error message.
