### ISSUE TITLE
problem with script

### ISSUE THREAD

**Issue by jimfs** [atom-ide-community/atom-script#817]
I deal with a problem when i try to instal sctript in order to run the code via atom and it says there is a en error.Now the error is gone but when i press the install button it loads but it isnt installed either.

**Comment by viyatgandhi** [comment]
@jimfs are you getting the same error message as #815 ? I am also unable to install the script.

**Comment by jimfs** [comment]
npm ERR! tar.unpack untar error......
.34.5" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! path c:\Temp\apm-install-dir-116127-5008-wwahea\node_modules\script\node_modules\ansi-to-html\node_modules\karg\Icon
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, open 'c:\Temp\apm-install-dir-116127-5008-wwahea\node_modules\script\node_modules\ansi-to-html\node_modules\karg\Icon
'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
That's the error i was talking about in my first post! @viyatgandhi so yes it's the same!Hope that someone with further knoledge can help us!It's a beautiful code editor!

**Comment by barthr** [comment]
#https://github.com/npm/npm/issues/11702

I had the same issue it was inside the karg package which couldn't create a file on windows.
I've tried to manually install it but I can't get it working either....

**Comment by dhh-hss** [comment]
@jimfs I'm just curious if this might be related. Do you have **Git** installed? Script relies on **Git** being installed to install some of its dependencies. (As do some other packages available for **Atom**. So a good idea to have.)

**Comment by jimfs** [comment]
Basically thanks a lot all of you for your replies.! :) @dhh-hss  yeah it is already installed.I found out via cmd.I am still trying to learn python through this annoying white script awful..no autocomplete not able to correct the code instantly etc..!As i can see it's a problem widely known.

**Comment by dhh-hss** [comment]
@jimfs Argh, okay. I see. I actually stumbled upon this, then I wanted to make a video for actually learning Python. I need to make a video for Windows, on how to get started there. (In Danish, I work at a Danish E-Learning company.) Windows is annoying, but you have to get everyone on a "base" level at least. Everybody doesn't sit on a UNIX based machines, after all. Hehe. Like I do.

If you want to get something going quickly for Python development in Atom. Install the following packages: **script**, **linter-flake8**, **linter**. (**linter-flake8** will install **linter**, the base package if you have **Git** installed.) **flake8** itself can be installed from pip, with `pip install flake8`. I hope this was helpful for getting started with Python and in Atom. :+1: (**flake8** is live code feedback and much more.)

**Comment by jimfs** [comment]
@dhh-hss Thanks a lot for your help man!I 'll try to follow your instructions and see what happens.I would like to see your attempt for making a python tutorial too either on linux or windows.Personally i love linux.Recently i have installed the fedora distro but i am kind newbie right now! thumbs up to @dhh-hss !!

**Comment by dhh-hss** [comment]
@jimfs Make sure that **Git** is in your **PATH**' variable on (especially) **Windows**. APM (Atom Package Manager) won't be able to use it otherwise.

On **Linux**. (Specfically Fedora in this case.) Everything should be done automatically through your package manager. (Yum.) Just run the following command in the Terminal: `sudo yum install git-all`

I'm running Kubuntu. (KDE and Ubuntu.) On my workstation at the office. My **PATH** variable looks like this:

```shell
dhh@dhh-HP:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
dhh@dhh-HP:~$ which git
/usr/bin/git
dhh@dhh-HP:~$ 
```
And as you can see, when I use `which git` it gives me the path for **/usr/bin/git**. Which also is a parth of my $PATH variable on the system. (`echo $PATH | grep "/usr/bin"` should colour the output, so it's easier to spot in the long $PATH string.)

```shell
dhh@dhh-HP:~$ echo $PATH | grep "/usr/bin"
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
dhh@dhh-HP:~$ 
```
As for the videos, I only make them in Danish. But there are some good once out there in "YouTube-land" and beyond, in English. :+1:

**Comment by SkaviCos** [comment]
Hi, whats wrong with  my "option" on "Script"?

3+2; 

"node" �� ����� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� �������� 䠩���.
[Finished in 0.092s]
