### ISSUE TITLE
Failed Atom install

### ISSUE THREAD

**Issue by spolel** [atom-ide-community/atom-script#820]
When I try to install I get this error :
Installing “script@3.5.2” failed.Show output…

**Comment by viyatgandhi** [comment]
@Fufl0  facing same error message as  #815 ?

**Comment by dhh-hss** [comment]
You need Git installed on your system to install script through APM. (Atom Package Manager.) I stumbled upon this myself on a fresh installation of my OS.

**Comment by karottc** [comment]
This is new problem:

error message is below:

npm ERR! Command failed: Cloning into bare repository 'C:\Users\karottc.atom\
apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.128]: errno=No error
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

I hava already installed git and set PATH variable.

**Comment by eadasiak** [comment]
I've got the same problem as @karottc, although I'm on a Mac.  git is installed and in my path.  Would appreciate any suggestions.  Other git interactions with github outside of the atom package manager work fine.

```
npm ERR! Command failed: Cloning into bare repository '/Users/eadasiak/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.130]: errno=Operation timed out
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/v_/73_dbw0s42ddhkn8ylk52f5h0000gn/T/apm-install-dir-11631-75591-wxteno/npm-debug.log
```

**Comment by dhhdev** [comment]
@karottc and @eadasiak - According to what I could find on Google. That error could possibly be firewall issues. Apparently the git protocol uses port 443 for the main repository and port 9418 for submodules.

You could try to use https instead or open up the ports. It's up to you. There are two ways to force git to use a specific protocol:

1.) Change your ~.gitconfig file manually. Open up your ~.gitconfig file and paste in the following. The snippet should be self explanatory.
```
[url "https://"]   
    insteadOf = git://
```

2.) Or, you could simply type the following in a Terminal window. (Git Bash for Windows users.)
```
git config --global url."https://".insteadOf git://
```

I hope this helps you both.

**Comment by fkfk** [comment]
've got the same problem as @karottc and @eadasiak, on Windows.
But trying install on Linux, successfully installed.

```
$ git --version
git version 2.8.1

$ git config --global -l
http.proxy=<my proxy addr>
core.autocrlf=false
core.safecrlf=true
user.name=Koutarou Tanaka
user.email=from.kyushu.island@gmail.com
url.https://.insteadof=git://

$ apm install script
Installing script to C:\Users\fkfk\.atom\packages failed

npm WARN addRemoteGit Error: Command failed:
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm WARN addRemoteGit  git://github.com/monsterkodi/node-simple-plist.git resetting remote C:\Users\fkfk\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! git clone --template=C:\Users\fkfk\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\fkfk\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: Cloning into bare repository 'C:\Users\fkfk\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! git clone --template=C:\Users\fkfk\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\fkfk\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: fatal: Unable to look up github.com (port 9418) (Temporary failure in name resolution)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\opt\\Atom\\resources\\app\\apm\\bin\\node.exe" "D:\\opt\\Atom\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\fkfk\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\fkfk\\.atom\\.apmrc" "install" "D:\\opt\\msys32\\tmp\\d-116311-2396-15dz5pn\\package.tgz" "--target=0.34.5" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\fkfk\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: Unable to look up github.com (port 9418) (Temporary failure in name resolution)
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by eadasiak** [comment]
@dhhdev - thanks for the advice!  There was indeed a firewall blocking outbound traffic on non-standard ports that was getting in the way.  I've since been able to get around the problem and re-install the package.  Thanks again!

**Comment by DemersM** [comment]
https://github.com/rgbkrk/atom-script/issues/881

**Comment by dhhdev** [comment]
@fkfk It sounds like you're having path issues. Make sure that Git is properly installed. The installer for Windows from https://git-scm.com/ has the option to add this correctly to your Windows PATH variable. The error you get, is most likely because port 9418 is not open. (Possibly in your router.) This is not an error as such, since most routers doesn't just have ports open out of the box left, right and center.

I would try and make sure the PATH variable is properly set and revert back to use git:// instead of https:// as you have set in Git config. I hope that helps.

@eadasiak I'm glad I could help you! 👍
