### ISSUE TITLE
Can not install script

### ISSUE THREAD

**Issue by cltsp** [atom-ide-community/atom-script#846]
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Users\Leacher\AppData\Local\atom\app-1.5.4\resources\app\apm\bin\node.exe" "C:\Users\Leacher\AppData\Local\atom\app-1.5.4\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\Leacher\.atom\.apm\.apmrc" "--userconfig" "C:\Users\Leacher\.atom\.apmrc" "install" "C:\Users\Leacher\AppData\Local\Temp\d-116218-12840-13w6rna\package.tgz" "--target=0.34.5" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into 'C:\Users\Leacher\AppData\Local\Temp\npm-12708-ee83b8a0\git-cache-6a23f3dc029b\5ff35d61ff600391ccd784a18616fa73c09e0aea'...
npm ERR! error: cannot spawn sh: No such file or directory
npm ERR! fatal: unable to fork
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

**Comment by nixel2007** [comment]
@zclzcllove is git installed on your machine?

**Comment by zclzcllove** [comment]
@nixel2007 Yes,I installed in C://Git and has seted environment variables.

**Comment by DemersM** [comment]
Same problem here. I have no problem installing any other package but script fail
