### ISSUE TITLE
Updating to “script@3.7.1” failed.

### ISSUE THREAD

**Issue by vratnagiri-veriskhealth** [atom-ide-community/atom-script#914]
I can't find this file: /tmp/apm-install-dir-11643-24305-8muvjz/npm-debug.log

But, here's the error message:
npm ERR! git clone --template=/home/i71178/.atom/.apm/_git-remotes/_templates --mirror git://github.com/monsterkodi/node-simple-plist.git /home/i71178/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541: Cloning into bare repository '/home/i71178/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! git clone --template=/home/i71178/.atom/.apm/_git-remotes/_templates --mirror git://github.com/monsterkodi/node-simple-plist.git /home/i71178/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541: fatal: read error: Connection timed out
npm ERR! Linux 3.19.0-58-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/i71178/.atom/.apm/.apmrc" "--userconfig" "/home/i71178/.atom/.apmrc" "install" "/tmp/d-11643-24305-1gp1odt/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository '/home/i71178/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: read error: Connection timed out
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11643-24305-8muvjz/npm-debug.log

**Comment by vratnagiri-veriskhealth** [comment]
I've tried update this package several times over the past month and it always fails with this message. The rest of my packages update fine.

**Comment by vratnagiri-veriskhealth** [comment]
I'm on Atom 1.7.3 on Ubuntu 14.04 LTS.

**Comment by vratnagiri-veriskhealth** [comment]
No luck when I uninstalled the package and tried to reinstall it.

**Comment by awkwrdm3** [comment]
npm ERR! git clone C:\Users\cpe\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\cpe\AppData\Local\Temp\npm-22536-a01246be\git-cache-10f93148dacb\5ff35d61ff600391ccd784a18616fa73c09e0aea: Cloning into 'C:\Users\cpe\AppData\Local\Temp\npm-22536-a01246be\git-cache-10f93148dacb\5ff35d61ff600391ccd784a18616fa73c09e0aea'...
npm ERR! git clone C:\Users\cpe\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\cpe\AppData\Local\Temp\npm-22536-a01246be\git-cache-10f93148dacb\5ff35d61ff600391ccd784a18616fa73c09e0aea: error: cannot spawn sh: No such file or directory
npm ERR! git clone C:\Users\cpe\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\cpe\AppData\Local\Temp\npm-22536-a01246be\git-cache-10f93148dacb\5ff35d61ff600391ccd784a18616fa73c09e0aea: fatal: unable to fork
npm ERR! git clone C:\Users\cpe\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\cpe\AppData\Local\Temp\npm-22536-a01246be\git-cache-10f93148dacb\5ff35d61ff600391ccd784a18616fa73c09e0aea: 
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\cpe\\AppData\\Local\\atom\\app-1.7.3\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\cpe\\AppData\\Local\\atom\\app-1.7.3\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\cpe\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\cpet13\\.atom\\.apmrc" "install" "C:\\Users\\cpe\\AppData\\Local\\Temp\\d-11649-20208-wg0q32\\package.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into 'C:\Users\cpe\AppData\Local\Temp\npm-22536-a01246be\git-cache-10f93148dacb\5ff35d61ff600391ccd784a18616fa73c09e0aea'...
npm ERR! error: cannot spawn sh: No such file or directory
npm ERR! fatal: unable to fork
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>



this is the error i'm getting... when i try to install... I can install any other package i want...

**Comment by jonathanmarvens** [comment]
@rgbkrk: I’m dealing with the same problem the other folks on here mentioned … can you please take a look?

**Comment by aswincsekar** [comment]
@rgbkrk : same problem not able to update script

Package Updates Available (1)
└── script 3.4.1 -> 3.7.3

Would you like to install these updates? (yes) 

Installing script@3.7.3 to /home/aswin/.atom/packages 
✗

npm ERR! git clone --template=/home/aswin/.atom/.apm/_git-remotes/_templates --mirror git://github.com/monsterkodi/node-simple-plist.git /home/aswin/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541: Cloning into bare repository '/home/aswin/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! git clone --template=/home/aswin/.atom/.apm/_git-remotes/_templates --mirror git://github.com/monsterkodi/node-simple-plist.git /home/aswin/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541: fatal: unable to connect to github.com:
npm ERR! git clone --template=/home/aswin/.atom/.apm/_git-remotes/_templates --mirror git://github.com/monsterkodi/node-simple-plist.git /home/aswin/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541: github.com[0: 192.30.252.128]: errno=Connection timed out
npm ERR! Linux 3.19.0-61-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/aswin/.atom/.apm/.apmrc" "--userconfig" "/home/aswin/.atom/.apmrc" "install" "/tmp/d-116511-16449-8qolr8/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository '/home/aswin/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.128]: errno=Connection timed out
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-116511-16449-4gj3bi/npm-debug.log
