### ISSUE TITLE
Javascript alert()

### ISSUE THREAD

**Issue by GregPriceDev** [atom-ide-community/atom-script#929]
Thanks for this package, I use it all the time!

I understand that script is using node and there is obviously no way to display alert(), confirm() or prompt() on the server side, but could those functions be ignored or mapped to console.log() so a reference error would not be triggered? Right now, I either manually rename each occurrence or comment the offending line.  

![screen shot 2016-05-15 at 4 18 26 pm](https://cloud.githubusercontent.com/assets/2280741/15277149/b8e8b1e2-1ab8-11e6-8857-d1593cfe86d7.png)

**Comment by aminya** [comment]
alter is not supported in Nodejs. You should use a polyfill.
