### ISSUE TITLE
Add support for special characters

### ISSUE THREAD

**Issue by Spidersouris** [atom-ide-community/atom-script#962]
Hey!

Would it be possible to add support for special characters? I'm French and some special characters appear as interrogative marks. Here's an example: http://i.imgur.com/pBkT0gk.png

Thanks.

**Comment by nixel2007** [comment]
You need to handle with unicode strings. Try to search another issues in this repo

**Comment by dbolton** [comment]
It looks like atom-script on Windows uses cp1252 (Windows 1252) encoding by default instead of utf-8.

As a work-around you can specify the encoding as utf-8 in your code for the system out and error streams:

```
import sys
import io

sys.stdout = io.TextIOWrapper(sys.stdout.detach(), encoding = 'utf-8')
sys.stderr = io.TextIOWrapper(sys.stderr.detach(), encoding = 'utf-8')

print ('汉语/漢語')
```

**Comment by yalov** [comment]
@Spidersouris it's `atom-script` package repository and you have  `atom-runner` package at screenshot.

@dbolton text in the `atom-script` output appeared after all `print()` had complited, how to fix that?
```
sys.stdout = io.TextIOWrapper(sys.stdout.detach(), encoding = 'utf-8')
sys.stderr = io.TextIOWrapper(sys.stderr.detach(), encoding = 'utf-8')

for i in range(1,100):
    sleep(0.02) # Time in seconds.
    print(i,"трактор")
```


 text in the `atom-script` output appeared line by line, but with wrong encoding:
```
for i in range(1,100):
    sleep(0.02) # Time in seconds.
    print(i,"трактор")
```

P.S. In either case, text in the `atom-runner` output appeared after all `print()` had complited.
