### ISSUE TITLE
Install Fail

### ISSUE THREAD

**Issue by rjschad** [atom-ide-community/atom-script#983]
Tried numerous time to install this, I have git installed and have no problems installing/cloning other pkgs from github using Atom. I have tried to no avail:
**git config --global url."https://".insteadOf git://**

This message appears to me to be a firewall/connectivity issue. Anyone else experience this ? I am running the latest version of OSX 10.11.

npm ERR! git clone --template=/Users/teradata/.atom/.apm/_git-remotes/_templates --mirror git://github.com/monsterkodi/node-simple-plist.git /Users/teradata/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541: Cloning into bare repository '/Users/teradata/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! git clone --template=/Users/teradata/.atom/.apm/_git-remotes/_templates --mirror git://github.com/monsterkodi/node-simple-plist.git /Users/teradata/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541: fatal: unable to connect to github.com:
npm ERR! git clone --template=/Users/teradata/.atom/.apm/_git-remotes/_templates --mirror git://github.com/monsterkodi/node-simple-plist.git /Users/teradata/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541: github.com[0: 192.30.252.122]: errno=Operation timed out
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/teradata/Downloads/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/teradata/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/teradata/.atom/.apm/.apmrc" "--userconfig" "/Users/teradata/.atom/.apmrc" "install" "/private/var/folders/dx/0ksjcpjx0l5130vgc4hz5wf00000gp/T/d-116527-31202-19ty9k6/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository '/Users/teradata/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.122]: errno=Operation timed out
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/dx/0ksjcpjx0l5130vgc4hz5wf00000gp/T/apm-install-dir-116527-31202-ko9ozk/npm-debug.log

**Comment by rjschad** [comment]
Fixed. Firewall issue.

**Comment by NileshJarad** [comment]
I have same problem while installing (:

**Comment by ztyoung86** [comment]
I'm facing the same issue, could you please share the solution? I'm behind a firewall and outbound port is limited in 80 and 443, so I can only use https instead of git://.
