### ISSUE TITLE
npm install script fails - works for other packages?

### ISSUE THREAD

**Issue by zenmaster24** [atom-ide-community/atom-script#997]
Hi,

When I try and install script from the command line, I get the below error:

`npm ERR! Command failed: Cloning into bare repository 'C:\Users\zenmaster24\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.113]: errno=Invalid argument
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>`

Since this works for other packages, I was wondering if it was to do with the script repo having github issues, or possibly an npm issue?

Can I manually install the package? https://atom.io/packages/script does not mention a method.

Thanks!

**Comment by Akumetsu-Dev** [comment]
Hello, i found the solution, first GitHub windows Client not installed completely, what i mean the next step below, the installation process had to do it automatic, but did not.

1- C:\Users\<NameofUser>\AppData\Local\GitHub\PortableGit_<Serial>, in this folder you will find a batch named post-install you have to install it with admin permission.

2- Add to the environment variable the next path:
- C:\Users\<NameofUser>\AppData\Local\GitHub\PortableGit_PortableGit_<Serial>\usr\bin
- C:\Users\<NameofUser>\AppData\Local\GitHub\PortableGit_PortableGit_<Serial>\etc\ssh
- C:\Users\<NameofUser>\AppData\Local\GitHub\PortableGit_PortableGit_<Serial>\cmd
                    *GitHub didnt do this after the instalation, you have to do it manual.
![image](https://cloud.githubusercontent.com/assets/7697566/17557424/248b2978-5ee5-11e6-8e68-36bea6692561.png)

3- In the C:\Users\<NameofUser>\AppData\Local\GitHub\PortableGit_PortableGit_<Serial>\cmd, you will find 2 *.cmd files: "start-ssh-agent" and "start-ssh-pageant" run in with admin permission.
![image](https://cloud.githubusercontent.com/assets/7697566/17557449/3e3469ac-5ee5-11e6-94a6-2054c0fd363a.png)

4- Reboot windows and try install script.
